name = "gift-wishlist"
compatibility_date = "2024-12-01"

[site]
bucket = "./build"
pages_build_output_dir = "build"

[build]
command = "npm ci --legacy-peer-deps && npm run build"
output_dir = "build"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

kv_namespaces = [
    { binding = "GIFTS_KV", id = "cd7d5a4156264e1f8efc3612b0f26f1f" }
]